### ISSUE TITLE
麻烦请教作者关于论文中公式(5)推导的一个小问题

### ISSUE THREAD

**Issue by yangzy-yzy** [med-air/imFedSemi#1]
作者您好！非常感谢您这篇优秀且极具启发性的工作，我在仔细阅读您的论文时在公式(5)的推导处感觉有些困惑，可否麻烦您有空时指点一下，非常感谢！
![AM$QZY0~U(Z@ @8(MUV8J9](https://user-images.githubusercontent.com/45303446/179353981-82f7fc69-85d0-4548-829a-8380be7289ef.png)
上图是论文中公式(5)，将下面公式(3)代入公式(5)红框处：
![}QN_S5OMIX{)HIB7AWA_T88](https://user-images.githubusercontent.com/45303446/179354034-4da7192e-e96f-419d-9a4a-02c413feaf2a.png)
代入后可以得到：
![)G%E090)MU }Y3BCQ{}$4OT](https://user-images.githubusercontent.com/45303446/179354193-11973c27-cfc6-49a0-8dec-7d3ad8dd8b64.png)
那么上图中蓝框处的式子是否是相等呢，也就是说：
<img width="514" alt="image" src="https://user-images.githubusercontent.com/45303446/179354486-9ee47fd1-1c4c-4704-8077-c71c0876fb84.png">
<img width="231" alt="image" src="https://user-images.githubusercontent.com/45303446/179354495-209ba91d-baf2-4abf-a1bc-8162ada93f2b.png">
但到这里这个等式是成立的吗，不是应该等于下图才对吗
<img width="267" alt="image" src="https://user-images.githubusercontent.com/45303446/179354511-af8c24dc-cb14-4d72-bdb3-a1950d9effe0.png">

公式推到这里就很困惑，不清楚公式(5)的倒数第二个式子是如何推导到最后一个式子的。我的数学确实不太好，可能哪里理解的有问题，但卡在这里几天了也毫无进展，不知道可不可以麻烦作者有空时指点一下公式(5)的推导过程，打扰您了，万分感谢！！

**Comment by MeiruiJiang** [comment]
您好，十分感谢您对我们工作的兴趣！
对于最后一个等式，其中p(x)是可以被约分掉的。过程如下：
<img width="641" alt="image" src="https://user-images.githubusercontent.com/31134669/179660736-da7fb2dd-2ec0-498e-9dc4-93cb4937812c.png">

**Comment by yangzy-yzy** [comment]
好的，我明白了，感谢您的解答！！
