### ISSUE TITLE
RSNA ICH Detection task

### ISSUE THREAD

**Issue by wykn86** [med-air/imFedSemi#2]
Hello, I'm very interested in your work.  But my understanding of the RSNA ICH Detection task is that it is a multi-label classification task. Could you share me the converted dataset and the csv file? Thank you very much!

**Comment by MeiruiJiang** [comment]
Hello, many thanks for your interests in our work. 

RSNA ICH Detection contains some cases with multi-label, we randomly sampled slices which contain 1 of 5 subtypes.
We have provided csv files under this directory [data/brain_split](https://github.com/med-air/imFedSemi/tree/main/data/brain_split).
For the dataset downloading, please refer to the 'Dataset' section in README. 

Hope my answer addressed your concerns :)

**Comment by wykn86** [comment]
Thank you very much!
